### ISSUE TITLE
Определится со стеком

### ISSUE THREAD

**Issue by insrchofsnrs** [0C390312/splitly-core#3]
фронт: 
бек:
автоматизация:

**Comment by insrchofsnrs** [comment]
фронт: хз
бек: последний спринг бут , можно попробовать их новую фишку с нативным байткодом + все это конечно в докере крутится, потом может докер сворм заюзаем для кластаризации итд
автоматизация: гитхаб экшенс для всего и не ебет

**Comment by maleiEvgeni** [comment]
Фронт: vue + nuxt 
`бек: последний спринг бут , можно попробовать их новую фишку с нативным байткодом + все это конечно в докере крутится, потом может докер сворм заюзаем для кластаризации итд`  База если sql то postgresql если нет то mongo, авторизация делаем все в одно или поднимаем отдельный сервис, может не rest делать, а пробовать в модный  graphql. хранение секретов вроде тут это платно
